FROM python:3.9
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY main.py main.py
COPY fashion fashion
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--workers", "1", "--port", "80"]
